{
    'name': 'GBS HR Payroll',
    'author': 'Odoo Bangladesh',
    'website': 'www.odoo.com.bd',
    'category': 'payroll',
    'version': "1.0.0",
    'license': 'LGPL-3',
    'depends': [
        'hr_payroll',
        # 'l10n_in_hr_payroll',
        'hr_employee_seniority',
        'gbs_hr_department_sequence',
        # 'gbs_hr_employee',
        # 'web.report_layout',
        'amount_to_word_bd',
        'hr_payroll_festival_bonus',
        # 'gbs_hr_attendance_report',
        # 'hr_payslip_monthly_report'
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/payslip_summary_wizard.xml',
        'wizard/inherited_hr_payroll_payslips_by_employees_views.xml',
        'wizard/provident_fund_generate_wizard.xml',
        'wizard/salary_report_wizard.xml',
        'report/payroll_report_view.xml',
        'report/payslip_batches_summary_template.xml',
        'report/monthly_provident_found_report.xml',
        'report/provident_fund_template.xml',
        'report/monthly_emp_loan_deduction.xml',
        'report/report_payslip_inherit.xml',
        'views/hr_contract_view.xml',
        'views/inherited_hr_payslip_run_views.xml',
        'views/hr_payslip.xml',
        'views/email_template.xml',
        'views/hr_payroll_line_report_views.xml',

    ],
    'summary': 'Shows payslip reports',
    'description':
        "This module shows HR Manager to print individual payslip PDF report ",
    'installable': True,
    'application': True,
}
