{
    'name': 'Purchase RFQ Comparison',
    'description': "This module are compatible for PR",
    'author': 'Odoo Bangladesh',
    'website': 'www.odoo.com.bd',
    'license': 'LGPL-3',
    'category': 'Purchase',
    'version': "1.0.0",
    'depends': [
        'mail',
        'purchase',
        'purchase_requisition',
        # 'gbs_purchase_order',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/rfq_wizard.xml',
        'wizard/rfq_email_template.xml',
        'report/rfq_report.xml',
        'report/rfq_send_report.xml',
        'report/comparative_bid_study_report.xml',
        'data/rfq_sequence.xml',
        'data/mail_template_data.xml',
        'views/pr_view.xml',
        'views/po_view.xml',
        'views/purchase_rfq_view.xml',
    ],
    'installable': True,
    'application': True,
}
