{
    'name': 'Olila HRMS',
    'description':
        "This module enables Olila HR",
    'author': 'Odoo Bangladesh',
    'website': 'www.odoo.com.bd',
    'category': 'Human Resources',
    'version': "1.0.0",
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'hr_employee_id',
        'hr_employee_age',
        'hr_employee_ssn',
        'hr_employee_academic',
        'hr_employee_children',
        'hr_employee_family',
        'hr_employment_history',
        'hr_employee_seniority',
        'hr_employee_orientation',
        'gbs_hr_attendance',
        'hr_unpaid_holidays',
        'hr_attendance_and_ot_summary',
        'hr_manual_attendance',
        'hr_ot_requisition_multi_levels_approval',
        'hr_holidays_multi_levels_approval',
        'gbs_hr_payroll',
        'hr_employee_attendance_payroll',
        'hr_employee_loan_payroll',
        'hr_employee_mobile_bills_payroll',
        'hr_other_allowance_payroll',
        'hr_other_deduction',
        'hr_payroll_top_sheet',
        'hr_skills',
        'hr_holidays',
        'hr_holidays_gantt',
        'route_plan_extended',
        'hr_work_entry_contract',
        'hr_recruitment',
        'website_hr_recruitment',
        'gbs_hr_attendance_report',
        'hr_employee_requisition',
        'hr_employee_asset',
        'hr_employee_assessment',
        'hr_employee_exit',
        'mla_hr_exit',
        'hr_employee_training',
        'multi_level_approval',
        'virdi_connector_mssql',
        'zk_biotime_connector_mssql',
        'hr_contract',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_security.xml',
        'data/application_template_view.xml',
        'views/inherit_hr_department_view.xml',
        'views/hr_hobbies_interest_view.xml',
        'views/license_type_view.xml',
        'views/grade_master_view.xml',
        'views/inherit_hr_employee_view.xml',
        'views/inherit_hr_contract_view.xml',
        'views/hr_employee_transfer_view.xml',
        'views/hr_employee_expense_view.xml',
        # 'views/inherit_hr_payslip_run_view.xml',
        'views/inherit_hr_holidays_public_view.xml',
        'views/inherit_hr_job_view.xml',
        'views/inherit_hr_leave_view.xml',
        'views/inherit_hr_application_view.xml',
        'views/incident_raise_view.xml',
        'views/inherit_menu.xml',
        'views/inherited_website_hr_recuitment_templates.xml',
        'views/mla_transfer.xml',
        'views/mla_expense_views.xml',
        'views/mla_incident_raise_views.xml',
        'views/mla_loan_request_views.xml',
        'views/mla_contract_views.xml',
        'views/mla_training_program_views.xml',
    ],
    'installable': True,
    'application': False,
}
